version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # 코드 변경 시 자동 반영, btc_session.session 포함됨
    environment:
      - OPENAI_API_KEY=your_key_here